### ISSUE TITLE
The copy option for job post link does not work

### ISSUE THREAD

**Issue by sekanderb** [CrewHRM/CrewHRM#82]
<img width="1028" alt="Screenshot 2024-04-21 at 12 00 59 AM" src="https://github.com/CrewHRM/CrewHRM/assets/3262638/012f7ee2-1bb2-46a6-9631-5c40107eb8b3">

**Comment by jayedul** [comment]
It works here. Any screenshot from console?

**Comment by sh-sabbir** [comment]
It's coming from the `node_modules/crewhrm-materials` package. `navigator.clipboard` is a secure context API. That's why copy is working on the demo site (with SSL) and not working on non-https websites like local environments. 

Ref: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard

**Comment by sh-sabbir** [comment]
Fixed. Will be released with next update
